controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Standard controller to handle the "Command Interface"
    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

# Configuration for the standard velocity controller
joint_group_velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

omnidirectional_driver:
  ros__parameters:
    # ----------------------------------------
    # Physical Robot Parameters
    # ----------------------------------------

    robot_radius: 0.124     # Distance from center to wheel contact point
    wheel_radius: 0.0325   # Physical radius of the wheel
    
    wheel_names: 
      - joint_1
      - joint_2
      - joint_3

    # ----------------------------------------
    # Kinematic Geometry
    # ----------------------------------------

    # Wheel mounting angles (Wheel_frame -> Robot_frame) [degrees]
    ## 3-wheel omni: 0°, 120°, 240° is standard
    ## For our robot: 270°, 30°, 150°
    wheel_angles_deg: [270.0, 30.0, 150.0]

    # Omni wheel roller angle (Roller_frame -> Wheel_frame) [degrees]
    ## For Omni-wheels: 0°
    ## For Mecanum-wheels: 45°
    roller_angle_deg: 0.0

    use_field_centric: false
